name: 'Upload a directory to Release Asset'
description: 'Upload the content of a directory to release asset to an existing release in your repository'
author: 'ci010'
inputs:
  upload_url:
    description: 'The URL for uploading assets to the release'
    required: true
  asset_dir_path:
    description: 'The path to the asset you want to upload'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
